### ISSUE TITLE
Stringify all keys

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/sass-json-vars#14]
Should alleviate #7 .

Since Sass maps are true hash maps, and JSON files are dictionaries, we should stringify all keys for consistency. This will eliminate confusion with the following:

```scss
body {
    color: map-get($colors, red);
}
```

vs

```scss
body {
color: map-get($colors, 'red');
}
```

The latter of which breaks because the importer is using the key `red`, which is a color type in Sass.
