### ISSUE TITLE
Colour keywords get converted to sass colours in json

### ISSUE THREAD

**Issue by leevigraham** [vigetlabs/sass-json-vars#7]
Hey guys,

given the following json and scss:

```json
{
    "colours": {
        "red": {
            "base": "#000"
        }
    }
}
```

```scss
@import "config.json";

@function palette($palette, $tone: 'base') {
    @return map-get(map-get($colours, $palette), $tone);
}

body{
    color: palette('red', 'base');
}
```

I get the following error:

`Syntax error: $map: null is not a map for `map-get' on line 16 of colours.scss`

Changing "red" to "r" in both the json and sass produces the expected result:

```css
body { color: black; }
```

My guess is that somewhere along the line the "red" is being converted to however sass stores colours.
